server:
  ip: localhost
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/proxyim?serverTimezone=GMT%2b8
    username: root
    password: teg
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  data:
#    mongodb:
#      host: localhost # mongodb?????
#      port: 27017 # mongodb??????
#      database: im # mongodb???????
mybatis:
  mapper-locations: classpath:mapper/*.xml  #????mybatis?xml??

#target-node: "http://127.0.0.1:5000"
#target-node: "http://182.92.133.82:5000"
target-node: "http://182.92.133.82:5000"